{% set version = "2.0.2" %}

package:
  name: robotframework-robocop
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/r/robotframework-robocop/robotframework-robocop-{{ version }}.tar.gz
    sha256: 582865bbc473213fea06da9fb7700e0e8563fc1cf6ea44ad99f55960bf2a7df2
  - folder: src
    url: https://github.com/MarketSquare/robotframework-robocop/archive/refs/tags/{{ version }}.tar.gz
    sha256: ffa7cc58ff6f181dedd7ac9daae1a0cb645b583fe6ddc060490b588b4bf8112f

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robocop=robocop:run_robocop

requirements:
  host:
    - pip
    - python >=3.6
    - robotframework >=3.2.2
    - toml >=0.10.2
  run:
    - jinja2 >=3.0,<4.0
    - python >=3.6
    - packaging >=21.0,<22.0
    - pathspec >=0.9,<0.10
    - robotframework >=3.2.2
    - toml >=0.10.2

test:
  source_files:
    - src/tests
  imports:
    - robocop
  commands:
    - pip check
    - robocop --version
    - robocop --help
    - cd src
    - python -c "__import__('pathlib').Path('pytest.ini').write_text('''[pytest]\\naddopts = -k 'not find_project_root_missing_but_git' ''')"
    - coverage run --source=robocop -m pytest
    - coverage report --fail-under=96
  requires:
    - coverage
    - pip
    - pytest
    - pytest-benchmark
    - pyyaml
    - toml

about:
  home: https://github.com/MarketSquare/robotframework-robocop
  summary: Static code analysis tool (linter) for Robot Framework
  license: Apache-2.0
  license_file: src/LICENSE
  doc_url: https://robocop.readthedocs.io
  description: |
    Robocop is a tool that performs static code analysis of Robot Framework code.

    It uses official Robot Framework parsing API to parse files and run number of
    checks, looking for potential errors or violations to code quality standards.

extra:
  recipe-maintainers:
    - bollwyvl
