{% set version = "2.8.1" %}

package:
  name: robotframework-robocop
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/r/robotframework-robocop/robotframework-robocop-{{ version }}.tar.gz
    sha256: 0581855780a86b16875666e6bb3f476a3d94580a53cfc69613154d54675fc6f1
  - folder: src
    url: https://github.com/MarketSquare/robotframework-robocop/archive/refs/tags/{{ version }}.tar.gz
    sha256: 69931a8b14ed392b1189c0367a993265d394831918503a2b38c659f6649f6e27

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robocop=robocop:run_robocop
  script_env:
    - COVERAGE_THRESHOLD=92

requirements:
  host:
    - pip
    - python >=3.6
    - robotframework >=3.2.2
    - toml >=0.10.2
  run:
    - jinja2 >=3.0,<4.0
    - packaging >=21.0,<23.0
    - pathspec >=0.9,<0.12
    - python >=3.6
    - python-dateutil >=2.8.1
    - pytz >=2022.1
    - robotframework >=3.2.2
    - tomli

test:
  source_files:
    - src/tests
  imports:
    - robocop
  commands:
    - pip check
    - robocop --version
    - robocop --help
  requires:
    - coverage
    - pip
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pyyaml
    - toml

about:
  home: https://github.com/MarketSquare/robotframework-robocop
  summary: Static code analysis tool (linter) for Robot Framework
  license: Apache-2.0
  license_file: src/LICENSE
  doc_url: https://robocop.readthedocs.io
  description: |
    Robocop is a tool that performs static code analysis of Robot Framework code.

    It uses official Robot Framework parsing API to parse files and run number of
    checks, looking for potential errors or violations to code quality standards.

extra:
  recipe-maintainers:
    - bollwyvl
