{% set version = "2.1.0" %}

package:
  name: robotframework-robocop
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/r/robotframework-robocop/robotframework-robocop-{{ version }}.tar.gz
    sha256: fe17eafea0953c96c9d5a6ac1ef090f706ad4cfcdf864bbfe52ada9c1bf7638d
  - folder: src
    url: https://github.com/MarketSquare/robotframework-robocop/archive/refs/tags/{{ version }}.tar.gz
    sha256: 7effd0a3d8e8af625d2bb3e1f60b1dceff01237af77d034f7653e7f8753bb4c4

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robocop=robocop:run_robocop
  script_env:
    - COVERAGE_THRESHOLD=93

requirements:
  host:
    - pip
    - python >=3.6
    - robotframework >=3.2.2
    - toml >=0.10.2
  run:
    - jinja2 >=3.0,<4.0
    - python >=3.6
    - packaging >=21.0,<22.0
    - pathspec >=0.9,<0.10
    - robotframework >=3.2.2
    - toml >=0.10.2

test:
  source_files:
    - src/tests
  imports:
    - robocop
  commands:
    - pip check
    - robocop --version
    - robocop --help
  requires:
    - coverage
    - pip
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pyyaml
    - toml

about:
  home: https://github.com/MarketSquare/robotframework-robocop
  summary: Static code analysis tool (linter) for Robot Framework
  license: Apache-2.0
  license_file: src/LICENSE
  doc_url: https://robocop.readthedocs.io
  description: |
    Robocop is a tool that performs static code analysis of Robot Framework code.

    It uses official Robot Framework parsing API to parse files and run number of
    checks, looking for potential errors or violations to code quality standards.

extra:
  recipe-maintainers:
    - bollwyvl
